Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/homebrew/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
authentication = get_authentication()
qi_api = QuantumInspireAPI(QI_URL, authentication)

projectq_backend = QIBackend(quantum_inspire_api=qi_api)
------------------

----- stdout -----
Enter email:
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m/var/folders/8x/rvvvq5l53w14bts1k4qx9zlx3q3ggf/T/ipykernel_16375/4165889473.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mauthentication[0m [0;34m=[0m [0mget_authentication[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mqi_api[0m [0;34m=[0m [0mQuantumInspireAPI[0m[0;34m([0m[0mQI_URL[0m[0;34m,[0m [0mauthentication[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mprojectq_backend[0m [0;34m=[0m [0mQIBackend[0m[0;34m([0m[0mquantum_inspire_api[0m[0;34m=[0m[0mqi_api[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/homebrew/anaconda3/lib/python3.10/site-packages/quantuminspire/credentials.py[0m in [0;36mget_authentication[0;34m()[0m
[1;32m    186[0m     [0;32mif[0m [0memail[0m [0;32mis[0m [0;32mNone[0m [0;32mor[0m [0mpassword[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    187[0m         [0mprint[0m[0;34m([0m[0;34m'Enter email:'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 188[0;31m         [0memail[0m [0;34m=[0m [0minput[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    189[0m         [0mprint[0m[0;34m([0m[0;34m'Enter password'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    190[0m         [0mpassword[0m [0;34m=[0m [0mgetpass[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/homebrew/anaconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m   1279[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1280[0m             [0mmsg[0m [0;34m=[0m [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1281[0;31m             [0;32mraise[0m [0mStdinNotImplementedError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1282[0m         return self._input_request(
[1;32m   1283[0m             [0mstr[0m[0;34m([0m[0mprompt[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

